# For original NeRF
nerf_params:
  # basic hyperparams to specify where to load/save data from/to
  basic:
    log_dir: logs
    dataset_name: blender
    scene: lego
  # model hyperparams
  model:
    use_viewdirs: False
    randomized: False
    ray_shape: cone  # should be "cylinder" if llff
    white_bkgd: False  # should be False if using llff
    override_defaults: True
    num_levels: 2
    num_samples: 128
    hidden: 256
    density_noise: 0.0
    density_bias: -1.0
    rgb_padding: 0.001
    resample_padding: 0.01
    min_deg: 0
    max_deg: 16
    viewdirs_min_deg: 0
    viewdirs_max_deg: 4
  # loss and optimizer hyperparams
  loss:
    coarse_weight_decay: 0.1
    lr_init: .001
    lr_final: .00005
    lr_delay_steps: 2500
    lr_delay_mult: 0.1
    weight_decay: .00001
  # training hyperparams
  training:
    factor: 2
    max_steps: 2500
    batch_size: 2048
    do_eval: False
    continue_training: True
    save_every: 1000
    device: cuda
  # visualization hyperparams
  visualization:
    chunks: 8192
    model_weight_path: log/model.pt
    visualize_depth: True
    visualize_normals: True
  # extracting mesh hyperparams
  mesh:
    x_range: [-1.2, 1.2]
    y_range: [-1.2, 1.2]
    z_range: [-1.2, 1.2]
    grid_size: 256
    sigma_threshold: 50.0
    occ_threshold: 0.2


# For SARNeRF
sar_exp_params:
  learn_params:
    LR: 0.001
    LR_final: .00005
    weight_decay: 0.00001
    scheduler_gamma: 0.9
    coarse_weight_decay: 0.1
    swa_start: .6
    betas: [ .9, .99 ]
    step_size: 1
  model_params:
    D: 2
    hidden: 256
    randomized: True
    ray_shape: cone
    num_levels: 1
    num_samples: 1024
    density_noise: .001
    density_bias: -1.
    rgb_padding: 0.001
    resample_padding: 0.01
    min_deg: 0
    max_deg: 16
    return_raw: False
    pulse_std: 781026276.4943413
  train_params:
    warm_start: False
    log_epoch: 100
    is_tuning: False
    save_model: True
    loss_landscape: False
    patience: 500
    max_epochs: 2000
    log_dir: ./logs
  dataset_params:
    data_path: /home/jeff/SDR_DATA/RAW/12172024/SAR_12172024_113146.sar
    data_center: [40.0935619700, -111.7683527700, 1353.06885]
    train_batch_size: 1
    val_batch_size: 1
    fft_sz: 8192
    az_samples: 16
    el_samples: 16
    num_workers: 0
    pin_memory: False
    split: .7
    collate: False