# For original NeRF
exp_params:
  learn_params:
    LR: 0.0005
    weight_decay: 0.1
    scheduler_gamma: 0.9
    coarse_weight_decay: 0.1
    swa_start: .6
    betas: [ .9, .99 ]
    step_size: 1
  model_params:
    D: 1
    hidden: 16
    randomized: False
    ray_shape: cone
    num_levels: 2
    num_samples: 32
    density_noise: 1
    density_bias: -1
    rgb_padding: 0.001
    resample_padding: 0.01
    min_deg: 0
    max_deg: 16
    return_raw: False
  train_params:
    warm_start: False
    log_epoch: 100
    is_tuning: False
    save_model: True
    loss_landscape: False
    patience: 500
    max_epochs: 1000
    log_dir: ./logs
  dataset_params:
    data_path: ./data/nerf_synthetic/nerf_synthetic/lego
    train_batch_size: 4096
    val_batch_size: 4096
    near: 0.
    far: 1.
    num_workers: 0
    pin_memory: False
    split: .7
    collate: False


# For SARNeRF
sar_exp_params:
  learn_params:
    LR: 0.0005
    weight_decay: 0.1
    scheduler_gamma: 0.9
    coarse_weight_decay: 0.1
    swa_start: .6
    betas: [ .9, .99 ]
    step_size: 1
  model_params:
    D: 8
    hidden: 128
    randomized: False
    ray_shape: cone
    num_levels: 2
    num_samples: 64
    density_noise: 1
    density_bias: -1
    rgb_padding: 0.001
    resample_padding: 0.01
    min_deg: 0
    max_deg: 16
    return_raw: False
    pulse_std: 510785839.02234054
  train_params:
    warm_start: False
    log_epoch: 100
    is_tuning: False
    save_model: True
    loss_landscape: False
    patience: 500
    max_epochs: 1000
    log_dir: ./logs
  dataset_params:
    data_path: /home/jeff/SDR_DATA/RAW/12172024/SAR_12172024_112906.sar
    train_batch_size: 1
    val_batch_size: 1
    fft_sz: 32768
    az_samples: 64
    el_samples: 64
    num_workers: 0
    pin_memory: False
    split: .7
    collate: False