# For original NeRF
nerf_params:
  # basic hyperparams to specify where to load/save data from/to
  basic:
    log_dir: logs
    dataset_name: blender
    scene: lego
  # model hyperparams
  model:
    use_viewdirs: True
    randomized: True
    ray_shape: cone  # should be "cylinder" if llff
    white_bkgd: False  # should be False if using llff
    override_defaults: True
    num_levels: 2
    num_samples: 128
    hidden: 256
    density_noise: 0.0
    density_bias: -1.0
    rgb_padding: 0.001
    resample_padding: 0.01
    min_deg: 0
    max_deg: 16
    viewdirs_min_deg: 0
    viewdirs_max_deg: 4
  # loss and optimizer hyperparams
  loss:
    coarse_weight_decay: 0.1
    lr_init: .001
    lr_final: .00005
    lr_delay_steps: 2500
    lr_delay_mult: 0.1
    weight_decay: .00001
  # training hyperparams
  training:
    factor: 2
    max_steps: 2500
    batch_size: 2048
    do_eval: False
    continue_training: True
    save_every: 1000
    device: cuda
  # visualization hyperparams
  visualization:
    chunks: 8192
    model_weight_path: log/model.pt
    visualize_depth: True
    visualize_normals: True
  # extracting mesh hyperparams
  mesh:
    x_range: [-1.2, 1.2]
    y_range: [-1.2, 1.2]
    z_range: [-1.2, 1.2]
    grid_size: 256
    sigma_threshold: 50.0
    occ_threshold: 0.2


# For SARNeRF
sarnerf_params:
  # basic hyperparams to specify where to load/save data from/to
  basic:
    log_dir: logs
    sdr_file: /home/jeff/SDR_DATA/RAW/12172024/SAR_12172024_113146.sar
    data_center: [40.093229, -111.768341, 1353.06885]
    nsam: 3062
    near_range: 3047.0906
    mpp: 1.1991699
    pulse_std: 741815608.4201782
    save_model: False
    model_weights_path: ./logs
    model_name: sarnerf
  # model hyperparams
  model:
    num_samples: 64
    fine_samples: 32
    hidden: 100
    param_hidden: 28
    hidden_siren: 58.920285341490356
    init_siren: 66.51829093481844
    network_depth: 2
    encoder_sigma: 13.768412101438003
    encoder_size: 5
    wavelength: 0.031228381041666666
    az_half_bw: 0.039269908169872414
    el_half_bw: 0.09599310885968812
    beta0: 2.661299599941358
    activation: silu
  # loss and optimizer hyperparams
  loss:
    lr_init: 0.0001
    lr_final: .00005
    lr_delay_steps: 10000
    lr_delay_mult: 0.1
    weight_decay: 0.1
    eikonal_weight: .1
    acc_weight: 1.
  # training hyperparams
  training:
    split: .7
    max_epochs: 2000
    max_steps: -1
    batch_size: 1
    device: cuda
    ray_samples: 8192
    num_workers: 0
    single_example: False
    distributed: False
    warm_start: False